all:
  hosts:
    vps:
      ansible_host: CHANGE_ME_IP

      # === 1er run : bootstrap en root sur port 22 ===
      ansible_user: root
      ansible_port: 22
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519

      # === Runs suivants : décommente et commente le bloc au-dessus ===
      # ansible_user: deploy
      # ansible_port: 4242
      # ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      # ansible_become: true
